- charts/bindplane/Chart.yaml
Updated the Chart to use BindPlane OP 1.10.0.
> Use bindplane 1.10.0

- charts/bindplane/Chart.yaml
Deploy to minikube
```bash
helm template bindplane \
--values test/cases/default/values.yaml \
charts/bindplane | kubectl apply -f -
```
Check image version:
```bash
ghcr.io/observiq/bindplane:1.12.0
```
> Default to BindPlane OP v1.12.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
Added the `BINDPLANE_LDAP_PROTOCOL` for the refactor code
> Fix: Added the BINDPLANE_LDAP_PROTOCOL env

- charts/bindplane/Chart.yaml
- Bump chart version to 0.0.40
- Bump app version to 1.21.0
> Updated chart and app version

- charts/bindplane/Chart.yaml
* Bumps the bindplane version to v1.24.0
> Use bindplane v1.24.0

- charts/bindplane/Chart.yaml
Use Bindplane OP release v1.28.0.
> Use bindplane v1.28.0

- charts/bindplane/Chart.yaml
> Use bindplane 1.29.0

- charts/bindplane/Chart.yaml
> Use BindPlane OP v1.30.0

- charts/bindplane/Chart.yaml
> feat: Update bindplane to 1.31.0

- charts/bindplane/Chart.yaml
> Use BindPlane 1.32.0

- .github/workflows/ci.yml
Due to an S3 issue, we should use the included version of kubectl, which was already being used in several places.
> fix(ci): Do not download kubectl from s3

- .github/workflows/ci.yml
- charts/bindplane/README.md
- charts/bindplane/templates/_helpers.tpl
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/transform-agent-service.yaml
- charts/bindplane/templates/transform-agent.yaml
- charts/bindplane/values.yaml
- Removed `enterprise` option (if the option exists in an existing values file, it will just be ignored)
- Removed all conditions that look for `.Values.enterprise`
- Updated helper to always use the `bindplane-ee` image
- Removed mention of enterprise in the docs
- Default EULA to `true` (this falls in line with our other deployment methods)
Existing deployment can update without issue. Basically this is just an image change, and is compatible with all previous configurations.
> Default to enterprise image with free tier license

- charts/bindplane/Chart.yaml
This reverts commit 0ffe6c227f8941438a9db8996402535844c18ef4.
> Revert "Update to bindplane 1.33 (#62)"

- charts/bindplane/Chart.yaml
> feat: Update bindplane to 1.33.1

- charts/bindplane/Chart.yaml
> bindplane 1.34

- charts/bindplane/Chart.yaml
> Use bindplane 1.34.1

- charts/bindplane/Chart.yaml
> Bindplane 1.35.0

- charts/bindplane/Chart.yaml
> Update to use v1.36.0

- charts/bindplane/Chart.yaml
> Use bindplane version 1.37.0

- charts/bindplane/Chart.yaml
> bindplane 1.38

- charts/bindplane/Chart.yaml
> Update Chart to new version

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/prometheus.yaml
> use rules config in dev

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> deps(bindplane): Upgrade to 1.40.0

- .github/workflows/ci.yml
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/templates/prometheus_config.yaml
- Updated to 1.41.0
- Fixed Prometheus recording rule per 1.41.0 release notes.
> deps(bindplane): Update to v1.41.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> deps(bindplane): Update to v1.42.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Upgrade to bindplane 1.44.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Update to BindPlane 1.45.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Update to BindPlane v1.46.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
Bumps the chart and app version, updates the chart README.
> Bump Chart and App version to 1.47.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
Enterprise users have the option to disable analytics.
> feat: Add option to disable analytics

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Update to BindPlane v1.49.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> chore: Update to BindPlane 1.50.0

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
Add Auth0 parameters for the `auth0` auth type. This is only intended to be used internally, not by end users.
> feat: Support extraEnv

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
Getting the params from the `extraEnv` ended up being complex, put them in `dev`
> fix: Get Auth0 params from dev

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane.yaml
- test/cases/default/values.yaml
Resolved a positioning and indentation issue. Added test case to ensure it is working.
> fix: extraEnv

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Use v1.51.0, bump chart version

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
When operating in HA, it can be desired to set a fixed pod count instead of using HPA.
> feat: Support replica count

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane.yaml
We need to set serviceName when using a statefulset.
> fix(statefulset): Service name for sts

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
The strategy used here is what we use in production.
> Configure "strategy" when operating BindPlane as a deployment

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> deps(bindplane): Update to v1.52.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> deps: BindPlane v1.53.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> chore: BindPlane v1.54.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> deps(bindplane): Update to v1.55.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
Updated chart app version to 1.57.0 and re-gen docs (which caught some missing things)
> deps(bindplane): Update to v1.57.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
Tracing was not working until I added the sampling option. Defaults to 1 (100% sent).
> fix(tracing): Set sampling rate

- .github/workflows/ci.yml
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Use BindPlane 1.58.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> BindPlane v1.59.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> BindPlane v1.60.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Bindplane 1.61.1

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> BindPlane v1.62.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Update to bindplane 1.63.1

- .github/workflows/ci.yml
- test/helper/postgres/postgres.tls.yaml
- test/helper/postgres/postgres.yaml
> chore(ci) Add plain text and tls postgres

- .github/workflows/ci.yml
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> deps(bindplane): BindPlane v1.64.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> BindPlane v1.65.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.66

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.67

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane.yaml
Include params for Auth0 management API when using Auth0 as auth type
> Use Auth0 management params

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane-jobs.yaml
Also set params for Auth0 Management API in the jobs template
> Use Auth0 management params in jobs

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.69

- .github/CODEOWNERS
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
Updated codeowners and chartfile to reflect current maintainers.
> chore: Update maintainers and doc links

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.70.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.71.0

- charts/bindplane/Chart.yaml
CI will fail until 1.71.1 release finishes.
> bindplane 1.71.1

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.73.0

- .github/workflows/helm.yml
Reverts observIQ/bindplane-op-helm#161
> Revert "feat: Trigger chart release on tagged versions"

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.74.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-nats.yaml
- Update default BindPlane version to v1.74.2
- Internal dev fixes
- Set missing auth0 options on nats pods. Allows us to run the chart with auth0+nats
> BindPlane v1.74.2

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.75.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> BindPlane 1.76.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane v1.80.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> BindPlane v1.81.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> BindPlane v1.82.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.83

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.84

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> default to v1.84.2

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/values.yaml
> default to bindplane 1.85.0

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> bindplane 1.86

- .github/workflows/ci.yml
- .github/workflows/helm.yml
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
> Bindplane v1.89.3
