observIQ/bindplane-op-helm

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/_helpers.tpl
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- Bumped chart version
- Added condition to helper for selecting the correct image repo
- Added all Postgres options, usable when enterprise is enabled and Postgres is set as the backend type
- bolt store is used when enterprise is not enabled or if postgres is not selected as the backend
- switch to ghcr.io instead of dockerhub, as ghcr.io hosts both open source and enterprise editions of bindplane
When bbolt is not the backend, a deployment is generated instead of a statefulset (this was already implemented). Deployments look similar but have the following changes
- kind: Deployment
- serviceName is no longer set
When enterprise is enabled and postgres is set as the backend, the following diff is expected
- kind: Deployment
- serviceName is no longer set
- image name is `bindplane-ee`
- …
> Add postgres backend as enterprise option

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/_helpers.tpl
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
Added support for Enterprise ldap auth.
- Added environment configuration for basic ldap options (server, port, bind dn / user, etc)
- Added optional tls
- Optional tls verification skipping
- Optional tls ca certificate via secret volume mount
Tested the following scenarios
- `authType`: `system` (basic auth works here)
- `authType`: `ldap` (with tls disabled, ldap w/ port 1389)
- `authType`: `ldap` (with tls enabled, ldaps w/ port 1636)
- tested with insecure true / false
- tested with and without ca certificate secret
Example values used
```yaml
enterprise: true
backend:
type: postgres
postgres:
host: postgres
username: root
password: password
database: bindplane
eventbus:
type: "" # pubsub
pubsub:
projectid: bpcli-dev
topic: iris-updates
config:
username: admin
password: admin …
```
> feat: Support ldap auth (Enterprise)

- README.md
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- doc/developing.md
- Added options for enabling OTLP tracing.
- Merged charts/bindplane/README.md into the main README
- Used [helm-docs](https://github.com/norwoodj/helm-docs) to generate configuration documentation at charts/bindplane/README.md
Tested against my own collector with OTLP receiver.
```yaml
...
trace:
type: otlp
otlp:
endpoint: 10.99.1.10:4317
insecure: true
...
```
```
...
- name: BINDPLANE_CONFIG_TRACE_TYPE
value: otlp
- name: BINDPLANE_CONFIG_OTLP_TRACING_ENDPOINT
value: 10.99.1.10:4317
- name: BINDPLANE_CONFIG_OTLP_TRACING_INSECURE_TLS
value: "true"
...
```
> feat: Tracing and documentation refactor

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/_helpers.tpl
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
Image name handling is somewhat clunky right now because we insert `-ee` into `image.repository` if `enterprise: true`. This is annoying when you are setting `image.repository` yourself, because you get an unpredictable output.
This PR refactors image handling by avoiding the `-ee` insertion if the user has set their own repository (new `image.name` option).
- Replaced `image.repository` with more appropriate `image.name` parameter
- Refactored the image.repository helper to handle default `image.name` values based on whether enterprise is enabled or not. This behavior is ignored if the user has specified their own image.name.
- Moved image tag handling to its own helper.
Tested the following value options:
```yaml
enterprise: false
```
```yaml
enterprise: true
image:
tag: abcd
``` …
> Refactor image name and tag handling

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/hpa.yaml
- charts/bindplane/values.yaml
Added HPA configuration when pubsub + deployment type are used.
The following options generate an HPA config:
```yaml
enterprise: true
eventbus:
type: pubsub
pubsub:
projectid: bpcli-dev
topic: test
backend:
type: postgres
postgres:
database: bindplane
username: postgres
password: password
autoscaling:
enable: true
```
```yaml
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
name: RELEASE-NAME-bindplane
spec:
minReplicas: 2
maxReplicas: 10
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: RELEASE-NAME-bindplane
metrics:
- type: Resource
resource:
name: memory
target:
type: Utilization
averageUtilization: 60
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 60
```
> feat: Add HPA config

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
TODO
- merge https://github.com/observIQ/bindplane-op-helm/pull/12 and rebase
- bump chart version
- regen chart values doc with `helm-docs`
Added email configuration with sendgrid with support for other backends in the future.
I deployed to a GKE cluster using postgres, pubsub, and openldap. When multi account is enabled, the email option is functional in the UI.
> feat: Support email invitations w/ Sendgrid

- charts/bindplane/templates/bindplane.yaml
When using an HPA, we want to avoid specifying the replicas in the deployment spec. The HPA will handle determining the correct replica count. If replicas are set in the deployment, the deployment will scale down during a rolling update.
If HPA is not in use, the deployment will default to one replica anyway.
Helm template shows one replica when statefulset is used and no replicas when deployment is used.
Statefulset:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
name: release-name-bindplane
namespace: default
labels:
app.kubernetes.io/name: bindplane
app.kubernetes.io/stack: bindplane
app.kubernetes.io/component: server
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
spec:
replicas: 1
selector:
...
```
Deployment:
```yaml
apiVersion: apps/v1
kind: …
```
> fix(hpa): Do not set replicas unless running as statefulset

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
Instead of defaulting to "bindplane" for server_url and remote_url, we should be using the helm deployment name (by default) and only using config.server_url / config.remote_url if the user deliberately species them in their values file.
This PR does the following
- removes default values for server_url and remote_url from values.yaml
- if server_url / remote_url are not set, derive the values from the deployment name
- if server_url  /remote_url are set, use them directly
With this method, the default server_url and remote_url will match the clusterIP service name. Users can set their own options which are more appropriate for their environment, like when running behind an ingress service + load balancer.
This change is backwards compatible. 
Deploying the chart with default values gives …
> fix: Default values for config.server_url and config.remote_url

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/ingress.yml
- test/cases/ingress/values.yaml
When using ingress
Setting `nginx.ingress.kubernetes.io/proxy-read-timeout` to 1 hour (from 60 seconds) will prevent collector opamp connections from being reset every 60 seconds.
Long term, we will be investigating keep alive to see if we can avoid setting an arbitrarily high value here. 
Changes
- bump chart version
- set proxy-read-timeout annotation in the ingress rule
- update ingress test case to use bindplane.local as the server / remote url
You can test with by deploying minikube w/ ingress
```bash
minikube start \
--nodes 1 \
--cpus 2 \
--memory 4g  \
--static-ip 192.168.49.2
minikube addons enable ingress
kubectl -n ingress-nginx wait deployment ingress-nginx-controller \
--timeout=120s --for condition=Available=True
```
Deploy with Helm and Kubectl
```bash
helm template bpop \ …
```
> Set proxy read timeout

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
Added the option to configure the bbolt volume claim template's storage class. This is useful for using non default storage class.
Changes
- Added storageClassName to volumeClaimTemplate config
- Added backend.bbolt.storageClass option to values.yaml
- Ran `helm-docs` to sync docs (past few releases have missed this)
GKE has the following by default.
```
NAME                     PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
premium-rwo              pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   7m47s
standard                 kubernetes.io/gce-pd    Delete          Immediate              true                   7m46s
standard-rwo (default)   pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true …
```
> feat: Expose storage class option for bbolt backend

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
In an effort to support OpenShift, we need to make pod and container [securityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) configurable by the user. This PR moves the hardcoded securityContext options to two new sections in the values file.
```yaml
podSecurityContext:
fsGroup: 65534
containerSecurityContext:
runAsNonRoot: true
runAsUser: 65534
readOnlyRootFilesystem: true
capabilities:
drop: ["ALL"]
```
This change behaves identically by default, but allows user to modify securityContext.
Does not fully resolve OpenShift support, but this PR does address one of the first steps identified by a user here https://github.com/observIQ/bindplane-op-helm/issues/16
> feat: Support configuring pod and container security context

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/prometheus.yaml
On GKE we get permission issues. Minikube works either way. The user id `65534` is what the prometheus process runs as, and maps to the `nobody` user.
```
/prometheus $ ls -la /prometheus/
total 20
drwxrwxrwx    4 nobody   nobody        4096 Dec  6 17:00 .
drwxr-xr-x    1 root     root          4096 Dec  6 17:00 ..
drwxr-xr-x    2 nobody   nobody        4096 Dec  6 16:57 chunks_head
-rw-r--r--    1 nobody   nobody           0 Dec  6 17:00 lock
-rw-r--r--    1 nobody   nobody       20001 Dec  6 17:00 queries.active
drwxr-xr-x    2 nobody   nobody        4096 Dec  6 17:00 wal
```
> fix(prometheus): Set permissions on /prometheus

- .github/workflows/ci.yml
Updated the test matrix to test against the latest release (1.29) as well as 1.25 and 1.27.
The k8s project maintains support for the last three minor versions, but we want to support a bit more than that.
> chore(ci): Test against 1.25, 1.27, 1.29

- .github/workflows/ci.yml
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus_config.yaml
- charts/bindplane/values.yaml
- test/cases/prometheus_sidecar/values.yaml
The Helm chart needs to be enhanced to support the latest measurement backend (Prometheus). We can deploy Prometheus as a sidecar when operating BindPlane as a single pod StatefulSet.
- Persistent volume claim for `/var/lib/prometheus/tsdb`
- Configmap with volume mounts to `/etc/prometheus`
Future PRs will include the following
1. Basic Auth
2. TLS
3. Advanced options such as queryPrefix and remote write (for using Mimir or other advanced architectures)
Tested by deploying to minikube.
```bash
minikube start
helm template charts/bindplane --values test/cases/prometheus_sidecar/values.yaml | kubectl apply -f -
```
Setup port forwarding.
```bash
kubectl port-forward pod/release-name-bindplane-0 3011:3001
```
```bash
kubectl port-forward pod/release-name-bindplane-0 -c prometheus 9999:9090 …
```
> feat(prometheus): Support StatefulSet with Prometheus sidecar

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
Added support for
- Query Path Prefix
- Remote Write Host, port, and path (endpoint)
- Auth
- TLS
I followed our [Prometheus Installation](https://observiq.com/docs/going-to-production/bindplane/prometheus#self-managed-prometheus) documentation when building my Prometheus test system.
Chart deployed from the branch with:
```bash
helm template \
--namespace default \
--values values.yaml \
bindplane \
charts/bindplane | kubectl apply -f - 
```
Port forwarding used to connect to the ui on port 3011.
```bash
kubectl port-forward pod/bindplane-0 3011:3001
```
Tested by ensuring topology view has active measurements.
```yaml
config:
secret_key: 12D8FB6E-1532-4A4C-97AF-95A430BE5E6E
prometheus:
enable: true …
```
> feat(prometheus): Support all Prometheus parameters

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
On slower systems, bindplane can fail to deploy because it takes too long to startup. The default cpu / memory values are too low in general, and [fall outside of our recommended sizing](https://observiq.com/docs/advanced-setup/installation/prerequisites).
To combat this, I have boosted the default resources and exposed each healthcheck in the values file.
- Boosted default CPU request to `1000m` (one core)
- Boosted default memory request to `1000Mi`
- Boosted default memory limit to `1000Mi`
- Exposed startup, readiness, and liveness probes in the values file
First, deploy the `main` branch in order to test upgrading to this branch.
```bash
minikube start
```
Create `values.yaml` file:
```yaml
config:
secret_key: 12D8FB6E-1532-4A4C-97AF-95A430BE5E6E …
```
> feat: Boost default resources and support configuring healthcheck probes

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/prometheus.yaml
When upgrading a StatefulSet to use a Prometheus sidecar, the StatefulSet needs to be deleted first. We need the volume reclaim settings to be set to "retain" to avoid dataloss. When the new StatefulSet is created, it will attach to the same volume and avoid dataloss.
You can learn more here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention
Start minikube: `minikube start`
Create the following `values.yaml` file.
```yaml
config:
secret_key: 12D8FB6E-1532-4A4C-97AF-95A430BE5E6E
dev:
collector:
create: true
```
Deploy 
```bash
helm template --values ./values.yaml charts/bindplane | kubectl apply -f -
```
Port forward and connect to the UI:
```bash …
```
> fix(volume): Reclaim persistent volumes when the StatefulSet is deleted

- .github/workflows/ci.yml
- README.md
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
- values/large.yaml
- values/small.yaml
Added a new option, `config.licenseUseSecret`. When true, the license will be read from the "bindplane" secret. This option is only considered if `config.license` is not set. If both options are not set, the license will not be set in the environment (this is the existing behavior).
> feat(secret): Support reading the license key from secret

- .github/workflows/ci.yml
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- test/cases/volume/values.yaml
Users can define custom volume and volume mount configurations. This is useful for mounting secret provider class secrets.
I added a test cases that drops in an emptyDir volume.
```yaml
config:
secret_key: 12D8FB6E-1532-4A4C-97AF-95A430BE5E6E
extraVolumes:
- name: cache-volume
emptyDir:
sizeLimit: 500Mi
extraVolumeMounts:
- mountPath: /tmp/cache
name: cache-volume
```
The resulting manifest runs great. It has the correct indentation/formatting.
```yaml
...
volumeMounts:
- mountPath: /data
name: release-name-bindplane-data
- mountPath: /tmp/cache
name: cache-volume
...
volumes:
- emptyDir:
sizeLimit: 500Mi
name: cache-volume
...
```
If I exec into the container, I can create files. The container …
> feat: Support arbitrary volumes

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/values.yaml
Instead of hardcoding `ghcr.io/observiq/bindplane-prometheus` for the Prometheus sidecar and statefulset, it is now an option at `prometheus.image.name` defaulting to `ghcr.io/observiq/bindplane-prometheus`. 
Works great w/ the following:
```bash
minikube start
helm template --values test/cases/default/values.yaml charts/bindplane | k apply -f -
```
Wait for the images to come up, and then check to make sure they are running:
```bash
$ kubectl get pod
NAME                                                      READY   STATUS    RESTARTS   AGE
release-name-bindplane-0                                  1/1     Running   0          86s
release-name-bindplane-prometheus-0                       1/1     Running   0          2m7s
release-name-bindplane-transform-agent-59d7657d8f-6rrxr   1/1 …
```
> feat(prometheus): Support setting prometheus image name

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/values.yaml
- test/cases/labels/values.yaml
Added two new options
- `extraPodLabels`
- `prometheus.extraPodLabels`
These will add abitrary labels to the StatefulSet / Deployment's pod template (`spec.template.metadata.labels`, AKA pod labels).
```bash
minikube start
helm template charts/bindplane --values test/cases/labels/values.yaml | kubectl apply -f -
```
Once deployed, you can do a `get pod <name` on the bindplane and Prometheus pods, parse with jq.
```
➜  bindplane-op-helm git:(feat/extra-pod-labels) ✗ kubectl get pod release-name-bindplane-0 -o json | jq '.metadata.labels'
{
"app.kubernetes.io/component": "server",
"app.kubernetes.io/instance": "release-name",
"app.kubernetes.io/name": "bindplane",
"app.kubernetes.io/stack": "bindplane",
"controller-revision-hash": "release-name-bindplane-69d7695dff",
"extraKey": …
```
> feat: Support extra labels for bindplane and prometheus pods

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/prometheus.yaml
We should be setting `allowPrivilegeEscalation` to false. Prometheus does not require a privileged user or the ability to escalate its privileges.
> feat(security): Set "allowPrivilegeEscalation: false" in Prometheus container

- docs/example/gke/README.md
- docs/example/gke/values.yaml
Adds an example values file that is suitable for managing 20,000+ agents in K8s.
> docs(examples): GKE production example.

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/values.yaml
- test/cases/pubsub/values.yaml
Copied `bindplane.yaml` to `bindplane-jobs.yaml`. The new `jobs` deployment will deploy when the deployment type is "Deployment" (High availability).
Currently, jobs has the similar configuration as the main bindplane deployment. Notable changes:
- `BINDPLANE_MODE` is `all`
- Component label has value `jobs`
- This will keep the jobs pod out of ingress
- Has its own resource request and limit configuration
I think in the future we can refactor both deployments so they share more configuration. Specifically, environment variables. I would like to get more robust testing in place before making such a large change.
The jobs pod should only deploy when using postgres. When postgres is configured, the deployment type will be `Deployment`. When using bbolt, deployment type will be …
> feat: Add jobs pod when using high availabily deployment

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/_helpers.tpl
This will fix an issue where the user could be operating with an older version of the transform agent. Each time the chart is updated, the matching transform agent will be configured.
Requires BindPlane v1.56.0 or newer. Will mention this in the release notes.
```bash
$ helm template charts/bindplane | grep image | grep -v Pull                     
image: ghcr.io/observiq/bindplane-transform-agent:1.56.0-bindplane
image: ghcr.io/observiq/bindplane-ee:1.56.0
image: ghcr.io/observiq/bindplane-prometheus:1.56.0
```
> chore: Use tagged release for transform agent

- .github/scripts/tls.sh
- .github/workflows/ci.yml
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/configmap.yaml
- charts/bindplane/values.yaml
- test/cases/postgres/values.yaml
- test/helper/postgres/postgres.yaml
This PR requires BindPlane v1.56.0, which will release May 8th.
- Updated the test script ldap.sh to handle ldap and postgres certificates, for creating certs in CI
- Added or updated the following `backend.postgres` options
- sslmode
- sslsecret
- name: Name of the secret containing the optional certificates
- sslcertSubPath: Name of the key in the secret containing the client certificate
- sslkeySubPath: Name of the key in the secret containing the client private key
- sslrootcertsubPath: Name of the key in the secret containing the certificate authority used to verify the server certificates authenticity
Added an `initContainer` to `bindplane` and `bindplane-jobs` deployments. This container is used to configure certificate permissions. The postgres client will refuse to start if the …
> feat(postgres): Support TLS ca and client keypair as a secret

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane.yaml
Set the following in the env
- KUBERNETES_NAMESPACE_NAME: Current namespace name
- KUBERNETES_POD_NAME: Current pod name
- KUBERNETES_CONTAINER_NAME: "server" (the actual name of the container within the pod)
A future version of BindPlane will look these variables up when exporting OpenTelemetry metrics and traces from its instrumented code.
> chore(env): Set k8s environment variables

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- test/cases/postgres/values.yaml
- test/helper/postgres/postgres.tls.yaml
- test/helper/postgres/postgres.yaml
Setup minikube. Make sure you have a license in your environment at `$BINDPLANE_LICENSE`
```bash
minikube start --nodes 1 --cpus 4 --memory 12g 
kubectl create secret generic bindplane \
--from-literal=license=$BINDPLANE_LICENSE
minikube addons enable metrics-server
minikube addons enable ingress
```
Deploy Postgres. This will also deploy a secret to the `default` namespace, which will be used to test this PR.
```bash
kubectl apply -f test/helper/postgres/postgres.yaml 
```
```
$ kubectl get secret  postgres-credentials -o yaml
apiVersion: v1
data:
password: cGFzc3dvcmQ=
username: cG9zdGdyZXM=
```
Create a `values.yaml` with the following contents:
```yaml
config:
backend:
type: …
```
> feat(postgres): Support credential secret

- .github/PULL_REQUEST_TEMPLATE.md
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/service.yaml
Removes the word "client" from port 4222, to prevent istio from auto detecting the wrong protocol.
See
- https://github.com/istio/istio/issues/28623
- https://github.com/AgathEmmanuel/RentIt/commit/47902f9d951c0c8055e0fdbade971957fca9f003
> fix(istio): Rename nats client port to tcp to resolve istio protocol detection issue

- charts/bindplane/README.md
- test/cases/all/values.yaml
- test/cases/ingress/values.yaml
- test/cases/nats/values.yaml
This option has not been used for some time, use server url.
config.server_url will configure BindPlane's BINDPLANE_CONFIG_REMOTE_URL option.
> Remove legacy remote url

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/values.yaml
Kafka Event Bus has been deprecate in favor of [NATS](https://observiq.com/docs/advanced-setup/kubernetes-installation/server/components/eventbus) . NATS is embedded within BindPlane does not require third party infrastructure, and is 100% managed by the Helm chart.
Enabling NATS is as simple as this:
```yaml
eventbus:
type: nats
```
The chart will continue to function with Kafka, however, bug fixes and feature requests will result in urging the user to use NATS.
> chore(deprecate): Kafka event bus

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane.yaml
Add domain for Auth0 management API, which does not use our custom domain
> Add Auth0 mgmt domain param

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/templates/transform-agent.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
This PR updates the helm chart to support configuring affinity for Bindplane, NATS, Prometheus, and the Jobs pod(s).
A section to configure the affinity for each resource has been added to the `values.yaml` file and the templates have been updated accordingly.
This was tested manually using the following configuration when deploying the helm chart:
```yaml
config:
username: admin
password: admin
backend:
type: postgres
postgres:
host: postgres.postgres.svc.cluster.local
database: bindplane
username: postgres
password: password
maxConnections: 20
eventbus:
type: nats
replicas: 5
resources:
requests:
memory: 100Mi
cpu: 100m
limits:
memory: 100Mi
nats:
resources:
requests:
memory: 100Mi
cpu: 100m
limits:
memory: …
```
> feat: Support configuring affinity rules

- charts/bindplane/Chart.yaml
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/templates/transform-agent.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
This PR adds a `topologySpreadConstraints` configuration option to the `values.yaml` for the following deployments/resource:
- bindplane
- bindplane-nats
- bindplane-jobs
- prometheus
- transform_agent
> feat: add `topologySpreadConstraints` configuration option for deployments

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/templates/transform-agent.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
This PR adds the ability to configure the `nodeSelector` for bindplane, nats, jobs, prometheus, and tranform_agent deployments.
Tested with the following configuration:
```yaml
config:
username: admin
password: admin
backend:
type: bbolt
eventbus:
type: nats
replicas: 5
resources:
requests:
memory: 100Mi
cpu: 100m
limits:
memory: 100Mi
nats:
resources:
requests:
memory: 100Mi
cpu: 100m
limits:
memory: 100Mi
nodeSelector:
bindplane:
topology.kubernetes.io/zone: us-central1-b
nats:
topology.kubernetes.io/zone: us-central1-a
jobs:
topology.kubernetes.io/zone: us-central1-f
prometheus:
topology.kubernetes.io/zone: us-central1-f
transform_agent:
topology.kubernetes.io/zone: us-central1-a
```
Also tested when backend …
> feat: Node selector

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/_helpers.tpl
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/values.yaml
Added a `prometheus.image.tag` option for overriding the default Prometheus image tag. The tag defaults to the BindPlane version.
Currently, the default image is `ghcr.io/observiq/bindplane-prometheus:1.73.0`. When I set `prometheus.image.tag: 1.70.0`, the chart correctly uses that image. Here is a diff of the YAML output from `helm template`:
```
<           image: ghcr.io/observiq/bindplane-prometheus:1.73.0
---
>           image: ghcr.io/observiq/bindplane-prometheus:1.70.0
```
> feat: Support setting bindplane prometheus image tag

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/values.schema.json
- charts/bindplane/values.yaml
The current behavior is to deploy three NATS pods as a StatefulSet. This PR introduces the ability to deploy NATS as a deployment, defaulting to statefulset.
- When StatefulSet, set the following
- serviceName
- podManagementPolicy
- Set NATS routes based on deployment type
- StatefulSet: Use all three pod FQDN
- Deployment: Point to headless service
This change is motivated by some users being restricted to Deployments, they cannot use StatefulSets due to cluster restrictions in place by their organization.
I tested by deploying to GKE + CloudSQL with the following config:
```yaml
config:
username: redacted
password: redacted
server_url: redacted
ingress:
enable: true
host: redacted
class: nginx
backend:
type: …
```
> feat(nats): Support configuring NATS to run as a Deployment

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- test/cases/nats/values.yaml
Added a `metrics` config section, allowing users to enable OTLP or Prometheus metrics. The Prometheus metrics include the require annotations for being scraped by the [Kubernetes Prometheus Node](https://observiq.com/docs/resources/sources/kubernetes-prometheus-node) source.
When using the Prometheus metrics, users can configure the BindPlane node agent to autodetect and scrape the BindPlane pods for metrics.
When using OTLP, users can configure BindPlane to  push metrics to any OTLP receiver, such as the Node or Gateway agents.
Deploy minikube
```bash
minikube start
minikube addons enable ingress 
kubectl apply -f test/helper/postgres/postgres.yaml 
```
Create a license secret from `$BINDPLANE_LICENSE`
```bash
kubectl create secret generic bindplane \ …
```
> feat: Support OTLP and Prometheus APM metrics

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-nats.yaml
Adds missing env variables
- KUBERNETES_NAMESPACE_NAME
- KUBERNETES_POD_NAME
- KUBERNETES_CONTAINER_NAME
These are already set in the other deployments. We need these because BindPlane's internal metrics system looks them up to determine if it is running with Kubernetes or not.
> fix(nats): Set K8s namespace, pod, and container name environment variables

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.schema.json
When `eventbus.type: ""` (local), we should not deploy the jobs pod. We should also deploy the BindPlane pod with mode `all`.
It was assumed if "deployment type" was Deployment, that an event bus would be used for BindPlane HA. This is not the case. It is possible users would implement Postgres while sticking with local event bus (limited to one pod).
Deploying the jobs pod, and using mode "node" without an event bus will cause rollouts to fail.
Create `values.yaml` with the following.
```yaml
config:
backend:
type: postgres
postgres:
host: postgres.postgres.svc.cluster.local
database: bindplane
username: postgres
password: password
maxConnections: 20
resources:
requests:
memory: …
```
> fix: Do not deploy jobs pod when using local eventbus

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/templates/transform-agent.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
- Added `priorityClassName` for all all deployments
- Updated some docs for unrelated parameters
You can do this in your values file:
I deployed BindPlane HA w/ NATs.
I created a priority class:
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
name: high-priority
value: 1000000
globalDefault: false
```
And then I updated my values to include this:
```yaml
priorityClassName:
bindplane: "high-priority"
nats: "high-priority"
jobs: "high-priority"
prometheus: "high-priority"
transform_agent: "high-priority"
```
When I `get pod -o yaml`, I see:
```
priorityClassName: high-priority
priorityClassName: high-priority
priorityClassName: high-priority
priorityClassName: high-priority
priorityClassName: high-priority
priorityClassName: high-priority
priorityClassName: …
```
> feat: Support pod priorityClassName

- README.md
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
The chart assumes the cluster's service FQDN will be `.svc.cluster.local`. Generally this is true, but not always. It is also unnecessary. Services can look each other up by quering the service name or service name and namespace.
```
$ kubectl get service -n default
NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
bindplane-ha                         ClusterIP   10.96.110.178   <none>        3001/TCP   11m
bindplane-ha-nats-cluster-headless   ClusterIP   None            <none>        6222/TCP   11m
bindplane-ha-nats-headless           ClusterIP   None            <none>        4222/TCP   11m
bindplane-ha-prometheus              ClusterIP   10.103.27.175   <none>        9090/TCP   11m
bindplane-ha-transform-agent         ClusterIP   10.103.162.9 …
```
> fix: Remove svc.cluster.local fqdn assumption

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
The busybox image can be configured by setting `busybox_image`. This image is used in a few places for handling init processes.
> feat: Support configuring buxybox image

- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/templates/transform-agent.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
Similar to https://github.com/observIQ/bindplane-op-helm/pull/181, adds support for configuring terminationGracePeriodSeconds for all deployments.
I deployed BindPlane HA w/ NATs.
After adding the following to my values and re-deploying
```yaml
terminationGracePeriodSeconds:
bindplane: 30
nats: 31
jobs: 32
prometheus: 33
transform_agent: 34
```
I see this
```
terminationGracePeriodSeconds: 30
terminationGracePeriodSeconds: 32
terminationGracePeriodSeconds: 31
terminationGracePeriodSeconds: 31
terminationGracePeriodSeconds: 31
terminationGracePeriodSeconds: 33
terminationGracePeriodSeconds: 34
```
> feat: Support pod terminationGracePeriodSeconds

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/configmap.yaml
When Postgres sslSource is not "source", the config map for initializing the Postgres TLS emptydir volume should still be used, but it should skip copying the files from the secret to the emptyDir.
> fix: Skip mounting Postgres TLS certificats from secret when sslSource is 'manual'

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/templates/prometheus.yaml
- charts/bindplane/templates/transform-agent.yaml
- charts/bindplane/values.yaml
- test/cases/nats/values.yaml
Added support for initContainers. Each deployment has its own section. See the change to `test/cases/nats/values.yaml` for an example.
Init containers will allow users to perform custom actions before starting each service. Most users will not rely on this feature, it is for more advanced use-cases or testing.
e.g. I will be using this feature for generating certificates at startup, using `openssl`. 
I updated `test/cases/nats/values.yaml` to deploy initContainers. Working great. Each pod has its own basic init container.
> feat: Optional arbitrary init containers

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- test/cases/all/values.yaml
Added `command: []` and `args: []` options to the Values file, for overriding the default command and args. This is usefulf or users who need to pass flags to the BindPlane process.
1. Deployed latest chart version, observed `command` and `args` not set
2. Upgraded to this branch without configuring the new options, observed `command` and `args` not set
3. Configured `command` to `["/bindplane","serve"], left `args unconfigured, observed that `command` was set and the pods were running
4. Added `args` with `["--config", "/etc/bindplane/config.yaml"]` and observed `args` was set and the new pods **failed** to start, because /etc/bindplane/config.yaml does not exist (expected failure)
5. Removed `command` and `args` and observed the deployment going back to working
> feat: Expose command and args

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/transform-agent.yaml
- charts/bindplane/values.yaml
The chart supports `extraPodLabels` for Bindplane and Prometheus pods, but not Transform Agent. This PR addresses that. The transform agent extra labels are implemented the same as Bindplane / Prometheus.
I included this config snippet in my values file.
```yaml
transform_agent:
extraPodLabels:
user: joe
repo: bindplane-op-helm
```
When inspecting the deployed transform agent pod, I see the following labels. The last two are the extra labels added by the values file.
```yaml
apiVersion: v1
kind: Pod
metadata:
labels:
app.kubernetes.io/component: transform-agent
app.kubernetes.io/instance: bindplane
app.kubernetes.io/name: bindplane-transform-agent
app.kubernetes.io/stack: bindplane
pod-template-hash: 74cb87887d
repo: bindplane-op-helm
user: joe
```
> feat: Transform Agent extra pod labels

- README.md
- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/values.schema.json
- charts/bindplane/values.yaml
Updated documentation to mention that bbolt is deprecated. Bindplane v2 will use Postgres exclusively.
> chore: Mark bbolt as deprecated

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/service-account.yml
- charts/bindplane/values.yaml
- test/cases/nats/values.yaml
Added support for arbitrary service account annotations.
When running `helm template` with annotations defined (see test update), I get the following service account.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: release-name-bindplane
namespace: default
labels:
app.kubernetes.io/name: bindplane
app.kubernetes.io/stack: bindplane
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
annotations:
iam.gke.io/gcp-service-account: bindplane-sa
```
This annotation allows users to implement workload identity in GKE. You can read more about it here. https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
Closes https://github.com/observIQ/bindplane-op-helm/issues/177
> feat: Custom service account annotations

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.schema.json
- charts/bindplane/values.yaml
Bindplane v1.94 (unreleased) will introduce `BINDPLANE_AGENT_VERSIONS_CLIENTS` option. This config option allows the user to define their source of truth for syncing Bindplane OTEL Collector agent version releases. It will default to `github` and eventually default to `bdot`. 
Introducing this change now allows users with pre release builds to utilize the new option.
> feat(config): Support configurable agent version sync client

- charts/bindplane/Chart.yaml
- charts/bindplane/README.md
- charts/bindplane/templates/bindplane-jobs.yaml
- charts/bindplane/templates/bindplane-nats.yaml
- charts/bindplane/templates/bindplane.yaml
- charts/bindplane/values.yaml
- test/cases/ingress/values.yaml
A new `web_url` value has been added to expose the [BINDPLANE_WEB_URL](https://docs.bindplane.com/configuration/bindplane#web-url) environment variable. If not set, this defaults to the `server_url` value.
> feat: Expose BINDPLANE_WEB_URL environment variable as optional value
